apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-dep
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx-ingress
        image: dubblebee/k8s-marklogic:ml-nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 7997
          hostPort: 7997
        - containerPort: 7998
          hostPort: 7998
        - containerPort: 7999
          hostPort: 7999
        - containerPort: 8000
          hostPort: 8000
        - containerPort: 8001
          hostPort: 8001
        - containerPort: 8002
          hostPort: 8002
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      imagePullSecrets:
      - name: registry-secret